<?php
$form = $this->form;
$form->get('itemid'  )->setAttributes(['class'=>'form-control', 'placeholder'=>'Enter product itemid here'  ]);
$form->get('name'    )->setAttributes(['class'=>'form-control', 'placeholder'=>'Enter product name here'    ]);
$form->get('producer')->setAttributes(['class'=>'form-control', 'placeholder'=>'Enter product brand here'   ]);
$form->get('type'    )->setAttributes(['class'=>'form-control', 'placeholder'=>'Enter product type here'    ]);
$form->get('price'   )->setAttributes(['class'=>'form-control', 'placeholder'=>'Enter product price here'   ]);
$form->get('discount')->setAttributes(['class'=>'form-control', 'placeholder'=>'Enter product discount here']);
$form->get('color'   )->setAttributes(['class'=>'form-control', 'placeholder'=>'Enter product color here'   ]);
$form->get('regdate' )->setAttributes(['class'=>'form-control', 'placeholder'=>'Enter product reg date here']);
$form->get('submit'  )->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Add New Product</h1>
<p>Please fill out the following form and click the <i>Create</i> button.</p>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group"><?= $this->formRow($form->get('itemid'  )); ?></div>
        <div class="form-group"><?= $this->formRow($form->get('name'    )); ?></div>
        <div class="form-group"><?= $this->formRow($form->get('producer')); ?></div>
        <div class="form-group"><?= $this->formRow($form->get('type'    )); ?></div>
        <div class="form-group"><?= $this->formRow($form->get('price'   )); ?></div>
        <div class="form-group"><?= $this->formRow($form->get('discount')); ?></div>
        <div class="form-group"><?= $this->formRow($form->get('color'   )); ?></div>
        <div class="form-group"><?= $this->formRow($form->get('regdate' )); ?></div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
