<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('home'));
    $form->get('name'     )->setAttributes(['class'=>'form-control', 'placeholder'=>'Name']);
    $form->get('producer' )->setAttributes(['class'=>'form-control', 'placeholder'=>'Brand']);
    $form->get('type'     )->setAttributes(['class'=>'form-control', 'placeholder'=>'Type']);
    $form->get('pricefrom')->setAttributes(['class'=>'form-control', 'placeholder'=>'0']);
    $form->get('priceto'  )->setAttributes(['class'=>'form-control', 'placeholder'=>'1000']);
    $form->get('search')->setAttributes(['class'=>'btn btn-primary']);
    $form->prepare();
?>

<div class="jumbotron">
    <div class="row" id="filter" style="display:none">
        <div class="col-md-6">
            <h3><span class="zf-green">Filter by</span></h3>
            <p>
                <?php //echo $this->form()->render($form); ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php //echo $this->formLabel($form->get('name')); ?>
                    <?php //echo $this->formElement($form->get('name')); ?>
                    <?php //echo $this->formElementErrors($form->get('name')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('name')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('producer')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('type')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('pricefrom')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('priceto')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('datefrom')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('dateto')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('sortby')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('sortorder')); ?>
                </div>
                <?php echo $this->formElement($form->get('search')); ?>
                <?php echo $this->form()->closeTag(); ?>
            </p>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Products |
                    <a style='color:blue' href="<?= $this->url('product', ['action' => 'add']); ?>">add</a>
                </h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <tr id="tablehead">
                        <th>ItemId</th>
                        <th>Name</th>
                        <th>Brand</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Discount</th>
                        <th>Color</th>
                        <th>Registry date</th>
                    </tr>
                    <?php foreach ($this->products as $p): ?>
                        <tr>
                            <td><?= $p->getItemId();   ?></td>
                            <td><?= $p->getName();     ?></td>
                            <td><?= $p->getProducer(); ?></td>
                            <td><?= $p->getType();     ?></td>
                            <td><?= $p->getPrice();    ?></td>
                            <td><?= $p->getDiscount(); ?></td>
                            <td><?= $p->getColor();    ?></td>
                            <td><?= $p->getRegDate();  ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
                <?= $this->paginationControl($products,
                    'Sliding', 'application/partial/paginator',
                    ['route'  => 'application', 'filters'=> $this->filters]); ?>
            </div>
        </div>
    </div>

    <div class="col-md-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title" style="color:transparent;">Options</h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <tr>
                        <th style="color:transparent">===</th>
                        <th style="color:transparent">===</th>
                    </tr>
                    <?php foreach ($this->products as $p): ?>
                        <tr>
                            <td><a href="<?= $this->url('product', ['action' => 'edit',  'id' => $p->getId()]) . "?" . $this->filters; ?>">Edit</a></td>
                            <td><a href="<?= $this->url('product', ['action' => 'delete','id' => $p->getId()]) . "?" . $this->filters; ?>">Del</a></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    function addFilterButton() {
        var f = $("#filter");
        var el = $("<button/>");
        el.text("Show Filter");
        el.addClass("btn btn-success");
        el.click((e) => {
            f.toggle();
        });
        f.before(el);
        f.hide();
    }
    function addColumnSortOrder() {
        var jsortby    = $("input[name='sortby']");
        var jsortorder = $("input[name='sortorder']");
        var sortby    = jsortby.val();
        var sortorder = jsortorder.val();
        var cols = ['itemid', 'name', 'producer', 'type', 'price', 'discount', 'color', 'regdate'];
        $("th", $("#tablehead")).each(function (index, value) {
            var sp = $("<span>");
            sp.attr('col', cols[index]);
            sp.css('cursor', 'pointer');
            sp.css('color', cols[index] == sortby ? (sortorder == "ASC" ? "#444488" : "#448844"): '#aaaaaa');
            $(value).attr('col', cols[index]);
            $(value).wrapInner(sp).click((e) => {
                var col = $(e.target).attr('col');
                if (col == sortby) {
                    jsortorder.val(sortorder == "DESC" ? "ASC" : "DESC");
                } else {
                    jsortby.val(col);
                    jsortorder.val("DESC");
                }
                $("form").submit();
            });
        });
    }
    function onBootstrap() {
        addFilterButton();
        addColumnSortOrder();
    }
    $(document).ready(onBootstrap);
</script>